swagger: "2.0"
info:
  version: "1.0"
  title: "HelloWorldAPI"
host: "localhost:5555"
basePath: "/hello-world"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /greetings:
    get:
      operationId: "getGreetings"
      parameters:
      - name: "name"
        description: name of the caller
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/getGreetingsResponse"
        "401":
          description: "Access Denied"
definitions:
  getGreetingsResponse:
    required:
    - "dateTime"
    - "message"
    properties:
      message:
        type: "string"
      dateTime:
        type: "string"
        format: "date-time"