---
swagger: "2.0"
info:
  version: "1.0"
  title: "HelloWorldAPI"
host: "localhost:5555"
basePath: "/HelloWorldAPI"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /hello:
    get:
      operationId: "getHello"
      parameters:
      - name: "name"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/GetHelloResponse"
        "401":
          description: "Access Denied"
definitions:
  GetHelloResponse:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
